table PNB_LOOKUP
	lineageTag: 0b8fc573-8e9a-4249-bb9d-e64918a61dbc

	column 'Account No'
		dataType: int64
		formatString: 0
		lineageTag: 1dafb82a-065e-4fc5-81a4-f3ac400a3d85
		summarizeBy: none
		sourceColumn: Account No

		annotation SummarizationSetBy = Automatic

	column 'Account Name'
		dataType: string
		lineageTag: f840562b-7250-4c52-8b92-1616455a40e1
		summarizeBy: none
		sourceColumn: Account Name

		annotation SummarizationSetBy = Automatic

	column Défilement
		dataType: string
		lineageTag: 246f5ada-ee9d-43ae-a1d8-e648de9099da
		summarizeBy: none
		sourceColumn: Défilement

		annotation SummarizationSetBy = Automatic

	column 'Composant 3'
		dataType: string
		lineageTag: 950dc9a9-f706-4a1d-a168-6df43815db62
		summarizeBy: none
		sourceColumn: Composant 3

		annotation SummarizationSetBy = Automatic

	column 'Composant 2'
		dataType: string
		lineageTag: 453f1e85-7e66-4017-b45a-09d11d399d30
		summarizeBy: none
		sourceColumn: Composant 2

		annotation SummarizationSetBy = Automatic

	column 'Composant 1'
		dataType: string
		lineageTag: dac464e6-e185-40f1-a137-709cfefd91a5
		summarizeBy: none
		sourceColumn: Composant 1

		annotation SummarizationSetBy = Automatic

	column 'Composant 1.1'
		dataType: string
		lineageTag: 8b375833-8eb0-47f3-997e-dc31093972ba
		summarizeBy: none
		sourceColumn: Composant 1.1

		annotation SummarizationSetBy = Automatic

	column 'Composant 1.2'
		dataType: string
		lineageTag: bab8fcb4-b09f-479f-8f0c-3088af41ddfc
		summarizeBy: none
		sourceColumn: Composant 1.2

		annotation SummarizationSetBy = Automatic

	column 'Composant 1.3'
		dataType: string
		lineageTag: b1caef3f-c376-41ec-8355-4eb95945c9ff
		summarizeBy: none
		sourceColumn: Composant 1.3

		annotation SummarizationSetBy = Automatic

	column 'Composant 1.4'
		dataType: string
		lineageTag: 160732a9-5641-461c-a3ee-4f35d0fd08dd
		summarizeBy: none
		sourceColumn: Composant 1.4

		annotation SummarizationSetBy = Automatic

	column 'Composant 1.5'
		dataType: string
		lineageTag: 1d96c096-00b6-42bc-89dc-670b78698640
		summarizeBy: none
		sourceColumn: Composant 1.5

		annotation SummarizationSetBy = Automatic

	column Direction/Department
		dataType: string
		lineageTag: c930cfbc-8d68-49c7-aa91-d29989a39218
		summarizeBy: none
		sourceColumn: Direction/Department

		annotation SummarizationSetBy = Automatic

	column 'Cost Reduction-Priority Level'
		dataType: string
		lineageTag: bd0e3d0d-8272-4528-8363-4091334974f2
		summarizeBy: none
		sourceColumn: Cost Reduction-Priority Level

		annotation SummarizationSetBy = Automatic

	column 'Cost Reduction-Priority'
		dataType: string
		lineageTag: 7bddf598-1889-4104-9c02-dc0373cc7304
		summarizeBy: none
		sourceColumn: Cost Reduction-Priority

		annotation SummarizationSetBy = Automatic

	column 'Cost Reduction-Priority (Old)'
		dataType: string
		lineageTag: 1ae39ae7-51d2-4aa6-b597-d82c7c77f531
		summarizeBy: none
		sourceColumn: Cost Reduction-Priority (Old)

		annotation SummarizationSetBy = Automatic

	column 'Expenses Nature (for CC report)'
		dataType: string
		lineageTag: f3b8358a-2845-4a8b-95d9-f2b7a853c60c
		summarizeBy: none
		sourceColumn: Expenses Nature (for CC report)

		annotation SummarizationSetBy = Automatic

	column 'Nature of Expenses'
		dataType: string
		lineageTag: 9c0b5e04-7c17-4ef0-a1b4-7e15d6313844
		summarizeBy: none
		sourceColumn: Nature of Expenses

		annotation SummarizationSetBy = Automatic

	column 'Nature of Expenses (Comments)'
		dataType: string
		lineageTag: 7472628d-5e85-4612-a922-47de1d049850
		summarizeBy: none
		sourceColumn: Nature of Expenses (Comments)

		annotation SummarizationSetBy = Automatic

	column 'Allocate from HQ'
		dataType: string
		lineageTag: 17d5e576-0a28-4202-afa3-8ffa782035c9
		summarizeBy: none
		sourceColumn: Allocate from HQ

		annotation SummarizationSetBy = Automatic

	column 'Allocation Bassis'
		dataType: string
		lineageTag: 9cbc6255-23f2-492d-afcb-1283cb9d2340
		summarizeBy: none
		sourceColumn: Allocation Bassis

		annotation SummarizationSetBy = Automatic

	column 'Cost Type for Cost Sharing (HQ)'
		dataType: string
		lineageTag: 436781b0-069a-4ec4-bccf-8d1b6ca83198
		summarizeBy: none
		sourceColumn: Cost Type for Cost Sharing (HQ)

		annotation SummarizationSetBy = Automatic

	column ACCOUNT_HEADS_APPLICABLE
		dataType: string
		lineageTag: 245649bd-0fc8-42da-b8d8-a0bd28363035
		summarizeBy: none
		sourceColumn: ACCOUNT_HEADS_APPLICABLE

		annotation SummarizationSetBy = Automatic

	column GROUPING
		dataType: string
		lineageTag: 98ec7f71-533f-4b9d-a916-ff56f52c7957
		summarizeBy: none
		sourceColumn: GROUPING

		annotation SummarizationSetBy = Automatic

	column Group = if(PNB_LOOKUP[GROUPING]="","OTHERS",PNB_LOOKUP[GROUPING])
		lineageTag: 8d1cad97-43c9-4902-b32a-140c47f7f370
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition PNB_LOOKUP-835b6473-8c0c-4c2a-bc41-71b4c1064ac0 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("\\Phpfsbrtn01\Bureautique\Public\Data Analytics\12. Misc\03. Produit Net Bancaire (Profitability par client)\Dimension tables\Maping_PNB.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Account No", Int64.Type}, {"Account Name", type text}, {"Défilement", type text}, {"Composant 3", type text}, {"Composant 2", type text}, {"Composant 1", type text}, {"Composant 1.1", type text}, {"Composant 1.2", type text}, {"Composant 1.3", type text}, {"Composant 1.4", type text}, {"Composant 1.5", type text}, {"Direction/Department", type text}, {"Cost Reduction-Priority Level", type text}, {"Cost Reduction-Priority", type text}, {"Cost Reduction-Priority (Old)", type text}, {"Expenses Nature (for CC report)", type text}, {"Nature of Expenses", type any}, {"Nature of Expenses (Comments)", type any}, {"Allocate from HQ", type any}, {"Allocation Bassis", type any}, {"Cost Type for Cost Sharing (HQ)", type any}, {"ACCOUNT_HEADS_APPLICABLE", type text}, {"GROUPING", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

