table Targets_comm_market
	lineageTag: e7df0bed-572b-40dc-8d51-bbb765ad2be2

	column 'Director Regional'
		dataType: string
		lineageTag: 6c22e6e4-a1e4-4ff1-a554-235b86cf0f1f
		summarizeBy: none
		sourceColumn: Director Regional

		annotation SummarizationSetBy = Automatic

	column 'Director Regional User Principal'
		dataType: string
		lineageTag: deb18457-9366-417d-a108-49267c7c7019
		summarizeBy: none
		sourceColumn: Director Regional User Principal

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 443e5a4e-90ce-4815-8348-f74fadd72603
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 7ceb19a9-5ad6-4eeb-a496-4caa5b9f26cd
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column 'Responsible Commercial Market'
		dataType: string
		lineageTag: 00dadb80-b199-4531-bff2-9cea3d72d78b
		summarizeBy: none
		sourceColumn: Responsible Commercial Market

		annotation SummarizationSetBy = Automatic

	column 'Responsible Commercial Market User Principal'
		dataType: string
		lineageTag: d10cf7ba-dcdc-4351-9ef8-1cb91f6c92bc
		summarizeBy: none
		sourceColumn: Responsible Commercial Market User Principal

		annotation SummarizationSetBy = Automatic

	column 'Deposits(Decemer 22 + ↓)'
		dataType: decimal
		formatString: 0
		lineageTag: 9d0d090f-e3cc-4799-b4ac-3910ce7eb6b2
		summarizeBy: sum
		sourceColumn: Deposits(Decemer 22 + ↓)

		annotation SummarizationSetBy = Automatic

	column 'Loans(Decemer 22 + ↓)'
		dataType: decimal
		formatString: 0
		lineageTag: 340d4fdd-b7cd-4724-9ad8-ecd25e5c3c07
		summarizeBy: sum
		sourceColumn: Loans(Decemer 22 + ↓)

		annotation SummarizationSetBy = Automatic

	column NPL
		dataType: double
		lineageTag: faf3bc64-05af-4caf-9ac2-7e4dfb931c56
		summarizeBy: sum
		sourceColumn: NPL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CTO
		dataType: decimal
		formatString: 0
		lineageTag: d7c03f46-03a8-4580-99f3-91f393ca6c44
		summarizeBy: sum
		sourceColumn: CTO

		annotation SummarizationSetBy = Automatic

	column 'Client Aquisition(Decemer 22 + ↓)'
		dataType: int64
		formatString: 0
		lineageTag: fc949769-ec1d-4ace-b55c-6ef04b9c2f6e
		summarizeBy: sum
		sourceColumn: Client Aquisition(Decemer 22 + ↓)

		annotation SummarizationSetBy = Automatic

	column PNB
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 954262c9-e2dc-4178-a4d3-5669682f2421
		summarizeBy: sum
		sourceColumn: PNB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Packages
		dataType: int64
		formatString: 0
		lineageTag: cfb86986-a70c-4490-8b98-5d5ff4315dd1
		summarizeBy: sum
		sourceColumn: Packages

		annotation SummarizationSetBy = Automatic

	column Column = 'Targets_comm_market'[Region] & 'Targets_comm_market'[Market]
		lineageTag: 5964a3b5-1e4b-44ec-962a-1abff74afca0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Director Assistant'
		dataType: string
		lineageTag: c18b1713-5afe-4dfa-9269-5c7eaa448db7
		summarizeBy: none
		sourceColumn: Director Assistant

		annotation SummarizationSetBy = Automatic

	partition Targets_comm_market-a30bdebf-6e0f-479b-9fb2-b530808c52b8 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("\\Phpfsbrtn01\Bureautique\Data_Analytics\Global Dashboard TB\Targets_Comm_market_resp_market_regional_2023.xlsx"), null, true),
				    comm_market_Sheet = Source{[Item="comm_market",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(comm_market_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Deposits#(lf)(Decemer 22 + ↓)", Currency.Type}, {"Loans#(lf)(Decemer 22 + ↓)", Currency.Type}, {"NPL", type number}, {"CTO", Currency.Type}, {"Client Aquisition#(lf)(Decemer 22 + ↓)", Int64.Type}, {"PNB", Currency.Type}, {"Packages", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

