CREATE TABLE [dbo].[Cl_Bkcompens_Av] (

	[IDAV] varchar(max) NULL, 
	[IDFIC] varchar(max) NULL, 
	[TOPE] varchar(max) NULL, 
	[ETABD] varchar(max) NULL, 
	[GUIBD] varchar(max) NULL, 
	[COMD] varchar(max) NULL, 
	[CLEB] varchar(max) NULL, 
	[NOMD] varchar(max) NULL, 
	[AGEE] varchar(max) NULL, 
	[NCPE] varchar(max) NULL, 
	[SUFE] varchar(max) NULL, 
	[DEVE] varchar(max) NULL, 
	[DEV] varchar(max) NULL, 
	[MON] decimal(19,4) NULL, 
	[REF] varchar(max) NULL, 
	[DCOM] datetime2(6) NULL, 
	[ID_ORIG_SENS] varchar(max) NULL, 
	[ID_ORIG] varchar(max) NULL, 
	[ZONE] varchar(max) NULL, 
	[ETA] varchar(max) NULL, 
	[SYST] varchar(max) NULL, 
	[NATOPE] varchar(max) NULL, 
	[BATCHID] int NULL, 
	[BATCHDATE] datetime2(6) NULL, 
	[SYSTEMCODE] varchar(max) NULL, 
	[WORKFLOWNAME] varchar(max) NULL
);