CREATE TABLE [GoldWareHouse].[ClearingDim_test] (

	[ClearingID] bigint NULL, 
	[ClearingType] varchar(8000) NULL, 
	[ClearingCode] varchar(8000) NULL, 
	[FileBranchCode] varchar(8000) NULL, 
	[FileBranch] varchar(8000) NULL, 
	[FileCode] varchar(8000) NULL, 
	[FileStatus] varchar(8000) NULL, 
	[FileStatusDesc] varchar(8000) NULL, 
	[FileReference] varchar(8000) NULL, 
	[FileName] varchar(8000) NULL, 
	[FileStatusDate] datetime2(3) NULL, 
	[ClearingStatus] varchar(8000) NULL, 
	[ClearingStatusDesc] varchar(8000) NULL, 
	[InstrumentRef] varchar(8000) NULL, 
	[SenderInfo] varchar(8000) NULL, 
	[ReceiverInformation] varchar(8000) NULL, 
	[CheckDigit] varchar(8000) NULL, 
	[ReceiverName] varchar(8000) NULL, 
	[TranRef] varchar(8000) NULL, 
	[ClearingDate] datetime2(3) NULL, 
	[ClearingStatusReason] varchar(8000) NULL, 
	[ChequeID] bigint NULL, 
	[ChqVisStatus] varchar(8000) NULL, 
	[ChqNumber] varchar(8000) NULL, 
	[Narration] varchar(8000) NULL, 
	[BatchID] int NULL, 
	[BatchDate] date NULL, 
	[CreatedOn] date NULL, 
	[UpdatedOn] date NULL, 
	[SystemCode] varchar(8000) NULL, 
	[RowHash] varbinary(max) NULL, 
	[WorkFlowName] varchar(8000) NULL
);